data_config:
  filter_quality: medium
  max_length: 500
  min_length: 10
  preserve_conversational_tone: true
evaluation_config:
  metrics:
  - perplexity
  - response_relevance
  - conversational_flow
  - engagement
  test_split: 0.1
  validation_split: 0.2
lora_config:
  lora_alpha: 32
  lora_dropout: 0.1
  lora_r: 16
  target_modules:
  - q_proj
  - v_proj
task_info:
  conversation_count: 2
  description: Natural conversational responses
  output_directory: task_training/conversational_chat
  task_name: conversational_chat
training_config:
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 0.0003
  num_epochs: 2
  warmup_steps: 50
