data_config:
  filter_quality: high
  max_length: 800
  min_length: 30
  preserve_structure: true
evaluation_config:
  metrics:
  - perplexity
  - technical_accuracy
  - step_completeness
  - clarity
  test_split: 0.1
  validation_split: 0.2
lora_config:
  lora_alpha: 48
  lora_dropout: 0.1
  lora_r: 24
  target_modules:
  - q_proj
  - v_proj
  - k_proj
task_info:
  conversation_count: 2
  description: Step-by-step technical implementation guides
  output_directory: task_training/technical_implementation
  task_name: technical_implementation
training_config:
  batch_size: 3
  gradient_accumulation_steps: 4
  learning_rate: 0.0002
  num_epochs: 3
  warmup_steps: 100
