data_config:
  filter_quality: very_high
  max_length: 1500
  min_length: 20
  preserve_code_formatting: true
evaluation_config:
  metrics:
  - perplexity
  - code_quality
  - syntax_correctness
  - functionality
  test_split: 0.1
  validation_split: 0.2
lora_config:
  lora_alpha: 64
  lora_dropout: 0.05
  lora_r: 32
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
task_info:
  conversation_count: 2
  description: Code generation and programming assistance
  output_directory: task_training/code_generation
  task_name: code_generation
training_config:
  batch_size: 2
  gradient_accumulation_steps: 2
  learning_rate: 0.0001
  num_epochs: 5
  warmup_steps: 300
